name: CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - "*"
    types: [ opened, reopened, synchronize, edited ]

  push:
    branches:
      - "main"

jobs:
  coding-style:
    uses: ./.github/workflows/coding_style.yml

  # django-unit-test:
  #   needs: coding-style
  #   uses: ./.github/workflows/django_unit_test.yml
